FROM python:3.6
WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


ENV SLACK_TOKEN='xoxb-3171645816-395559020576-W9a5LBKekxmpnmQURZVCzd59'
ENV SLACK_NAME='sports_chatbot'
